### PR TITLE
SlimJS should be able to load fixtures written in TypeScript.

### PR DESCRIPTION
**Pull request by NicoleRauch**
For TypeScript, one can use ts-node to run SlimJS (was not sure where an how and if to document this).

### CODE REVIEW

**Comment by noamtcohen** [comment]
This looks great. I think it is a good idea to document this maybe add another MD file and link to it from the README?

**Comment by NicoleRauch** [comment]
OK, I will add a commit later in the day.

**Comment by NicoleRauch** [comment]
I've added a new page to the documentation. There is something that I could not figure out, and I've asked about this at the end of the documentation file. If you don't like this to be in the documentation, please feel free to revert the last commit.

**Comment by noamtcohen** [comment]
This is very good, thanks.

**Pull request merged**
